language: go

go:
  - 1.13.x

before_install:
  - go mod download

install:
  - go build -o knetlogin

script:
  - ls -lh knetlogin
  - go vet . ./cmd ./knet
  - golint . ./cmd ./knet

before_deploy:
  - go build -ldflags="-s" -o knetlogin
  - ls -lh knetlogin

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "knetlogin"
  cleanup: false
  on:
    tags: true

env:
  - GO111MODULE=on
