language: go

go:
  - 1.11.x
  - 1.13.x

before_install:
  - go mod download

install:
  - go build -o knetlogin
  - go install

script:
  - ls -lh knetlogin

before_deploy:
  - go build -ldflags="-s" -o knetlogin
  - ls -lh knetlogin

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "knetlogin"
  cleanup: false
  on:
    tags: true

env:
  - GO111MODULE=on
